version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8000:8000"
    links:
      - postgres
    container_name: server
    depends_on:
      - postgres
  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "3000:3000"
    container_name: ui
    links:
      - postgres
    depends_on:
      - postgres
      - server
volumes:
  postgres-data: